[package]
name = "ibkr-cp-api-client"
version = "0.1.0"
edition = "2021"
authors = ["Juan I Marquez"]
email = "juanim@pm.me"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.23.0", features = ["macros","rt-multi-thread"] }
reqwest = { version = "0.11.13", features = ["json"] }
serde_json = "1.0.91"
serde = { version = "1.0.152", features = ["derive"] }
tokio-tungstenite = "0.18.0"
futures-util = "0.3.25"
chrono = { version = "0.4.23", features = ["serde"] }
serde_repr = "0.1.10"
rust_decimal = { version = "1.27.0", features = ["serde-float"] }